import { Dimensions, StyleSheet } from "react-native";

const { width: screenWidth, height: screenHeight } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAFAFA",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
    padding: 16,
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0A0A0A",
  },
  headerPlaceholder: {
    width: 32,
  },
  progressContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    paddingVertical: 16,
    paddingHorizontal: 20,
  },
  progressStep: {
    alignItems: "center",
  },
  stepIndicator: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#E5E5E5",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
  },
  stepActive: {
    backgroundColor: "#6366F1",
  },
  stepNumber: {
    fontSize: 14,
    fontWeight: "700",
    color: "#737373",
  },
  stepNumberActive: {
    color: "#FFFFFF",
  },
  stepLabel: {
    fontSize: 12,
    color: "#737373",
  },
  stepLabelActive: {
    color: "#6366F1",
    fontWeight: "600",
  },
  progressLine: {
    flex: 1,
    height: 2,
    backgroundColor: "#E5E5E5",
    marginHorizontal: 8,
    maxWidth: 60,
  },
  progressLineActive: {
    backgroundColor: "#6366F1",
  },
  scrollView: {
    flex: 1,
  },
  stepContainer: {
    width: screenWidth,
    padding: 16,
    flex: 1,
  },
  packageInfo: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E5E5",
    marginBottom: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  packageTitle: {
    fontSize: 16,
    color: "#737373",
    marginBottom: 8,
  },
  tokensAmount: {
    fontSize: 32,
    fontWeight: "700",
    color: "#0A0A0A",
    marginBottom: 4,
  },
  bonusText: {
    fontSize: 14,
    color: "#10B981",
    fontWeight: "600",
    marginBottom: 8,
  },
  totalTokens: {
    fontSize: 18,
    fontWeight: "600",
    color: "#0A0A0A",
    marginBottom: 8,
  },
  price: {
    fontSize: 24,
    fontWeight: "700",
    color: "#6366F1",
  },
  qrContainer: {
    backgroundColor: "#FFFFFF",
    padding: 24,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E5E5",
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  qrImage: {
    width: 200,
    height: 200,
    borderRadius: 12,
    marginBottom: 16,
  },
  qrPlaceholder: {
    alignItems: "center",
    paddingVertical: 10,
  },
  qrText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0A0A0A",
    marginBottom: 8,
    textAlign: "center",
  },
  qrInstructions: {
    fontSize: 14,
    color: "#737373",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 8,
  },
  qrAccountInfo: {
    fontSize: 12,
    color: "#6366F1",
    textAlign: "center",
    fontWeight: "600",
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0A0A0A",
    marginBottom: 8,
    textAlign: "center",
  },
  sectionSubtitle: {
    fontSize: 14,
    color: "#737373",
    marginBottom: 24,
    lineHeight: 20,
    textAlign: "center",
  },
  inputContainer: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#0A0A0A",
    marginBottom: 8,
  },
  textInput: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E5E5",
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: "#0A0A0A",
  },
  uploadButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#FFFFFF",
    borderWidth: 2,
    borderColor: "#E5E5E5",
    borderStyle: "dashed",
    borderRadius: 12,
    padding: 20,
  },
  uploadButtonSuccess: {
    borderColor: "#10B981",
    borderStyle: "solid",
  },
  uploadButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#6366F1",
  },
  imagePreviewContainer: {
    marginTop: 12,
    position: "relative",
    alignItems: "center",
  },
  imagePreview: {
    // El touchable opacity para el preview
  },
  previewImage: {
    width: 200,
    height: 150,
    borderRadius: 12,
  },
  removeImageButton: {
    position: "absolute",
    top: 2,
    right: 2,
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  actionsContainer: {
    flexDirection: "row",
    gap: 12,
    marginTop: "auto",
    paddingTop: 20,
    paddingBottom: 10, // Espacio extra para safe area
  },
  primaryButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#6366F1",
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
    minHeight: 56,
  },
  primaryButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
    textAlign: "center",
  },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E5E5",
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
    minHeight: 56,
    minWidth: 100,
  },
  secondaryButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#6366F1",
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  stepContent: {
    flex: 1,
    justifyContent: "space-between",
  },
  bottomButtonContainer: {
    marginTop: "auto",
    paddingTop: 20,
    paddingBottom: 10, // Espacio extra para safe area
  },
  stepScrollContent: {
    flexGrow: 1,
    justifyContent: "space-between",
    paddingBottom: 10, // Espacio extra para safe area
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.95)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "100%",
    height: "100%",
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  closePreviewButton: {
    position: "absolute",
    top: 50,
    right: 20,
    zIndex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    borderRadius: 20,
    padding: 10,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  closePreviewTextButton: {
    position: "absolute",
    bottom: 50,
    backgroundColor: "rgba(0,0,0,0.7)",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
  },
  closePreviewText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  fullImage: {
    width: "100%",
    height: "100%",
  },
});
